infix using "C:\COUNTRIES\BD7R\BDVA7RFL.dct"

label variable qncluster "Cluster Number"
label variable qnhnumber "Household Number"
label variable qnmother "Line number of the mother"
label variable qnline   "Line number of child"
label variable qform    "Form type"
label variable qndivision "Division"
label variable qnresidence "Place of residence"
label variable qnintd   "Day of interview"
label variable qnintm   "Month of interview"
label variable qninty   "Year of interview"
label variable qnintnum "Interviewer number"
label variable qnresult "Result of household interview"
label variable qnvisits "Number of household visits"
label variable qnsuperv "Supervisor number"
label variable qnfedit  "Field editor number"
label variable qnedit   "Office editor number"
label variable qnkeyer  "Data entry clerk"
label variable qnresp   "Line number of respondent to verbal autopsy"
label variable qfinicd  "Final cause of death"
label variable vaweight "Weight"
label variable va_defacto "De facto resident"
label variable va_ucause_icd "Underlying cause of death"
label variable va_ucause_icd_des "Underlying cause of death description"
label variable qn201h   "Start time for interview (Hour)"
label variable qn201m   "Start time for interview (Minutes)"
label variable qn203    "Relationship to the deceased"
label variable qn204    "Lived with the deceased"
label variable qn302    "Sex of deceased"
label variable qn303d   "Date of Birth (Day)"
label variable qn303m   "Date of Birth (Month)"
label variable qn303y   "Date of Birth (Year)"
label variable qn303a   "Season when died"
label variable qn304    "Age of deceased when died"
label variable qn305d   "Date deceased die (Day)"
label variable qn305m   "Date deceased die (Month)"
label variable qn305y   "Date deceased die (Year)"
label variable qn307    "Place deceased died"
label variable qn401    "Illness that lead to death"
label variable qn402    "Cause of death 1"
label variable qn403    "Cause of death 2"
label variable qn403a   "Illness that led to death mentioned"
label variable qn502    "Number of births before this baby"
label variable qn503u   "Length of pregnancy unit"
label variable qn503n   "Length of pregnancy number"
label variable qn504    "Pregnancy ended earlier than expected"
label variable qn505    "Number of weeks premature"
label variable qn506a   "Mother suffered from High Blood pressure"
label variable qn506b   "Mother suffered from Heart Disease"
label variable qn506c   "Mother suffered from Diabetes"
label variable qn506d   "Mother suffered from Epilepsy/Convulsion"
label variable qn506e   "Mother suffered from Other medically diagnosed illness"
label variable qn507a   "Mother suffered from Vaginal Bleeding"
label variable qn507b   "Mother suffered from Smelly vaginal discharge"
label variable qn507c   "Mother suffered from Puffy face"
label variable qn507d   "Mother suffered from Headache"
label variable qn507e   "Mother suffered from Blurred Vision"
label variable qn507f   "Mother suffered from Convulsion"
label variable qn507g   "Mother suffered from Febrile illness"
label variable qn507h   "Mother suffered from abdominal pain"
label variable qn507i   "Mother suffered from Pallor and shortness of breath"
label variable qn507j   "Mother suffered from any other illness"
label variable qn508    "Child is single or multiple birth"
label variable qn509    "Birth Order of child"
label variable qn601    "Place the child was born"
label variable qn602    "Assisted the delivery"
label variable qn603    "Water break"
label variable qn604    "Hours after water break"
label variable qn605    "Water foul smelling"
label variable qn606    "Baby stopped moving in the womb"
label variable qn607    "When did the baby stop moving in the womb"
label variable qn608    "Birth attendant listen fetal heart sounds during labor"
label variable qn609    "Fetal heart sounds"
label variable qn610    "Excess bleeding during labor"
label variable qn611    "Mother had fever on the day labor started"
label variable qn612    "Duration of labor pain"
label variable qn613    "Normal vaginal delivery"
label variable qn614    "Type of delivery"
label variable qn615    "Which part of baby came first"
label variable qn616    "Umblical cord came out before the baby was born"
label variable qn701    "Size of the baby at birth"
label variable qn701a   "Baby born more than four weeks early"
label variable qn702    "Baby is premature"
label variable qn703u   "Duration of pregnancy (units)"
label variable qn703n   "Duration of pregnancy (Number)"
label variable qn704    "Weight in Kgs"
label variable qn705    "Anything applied to the umblical cord"
label variable qn706    "What was applied in the umblical cord"
label variable qn707    "Signs of injury or broken bone"
label variable qn708    "Location of signs of injury"
label variable qn709    "Signs of paralysis"
label variable qn710    "Baby had malformations"
label variable qn711    "Kind of malformation"
label variable qn712    "Color of baby at birth"
label variable qn713    "Baby breathed after birth"
label variable qn714    "Baby given assistance to breathe"
label variable qn715    "Baby ever cry after birth"
label variable qn716    "Baby ever moved"
label variable qn718    "Baby was born dead"
label variable qn719    "Baby was macerated"
label variable qn801    "Baby suffered from an injury or accident"
label variable qn802    "Kind of injury or accident"
label variable qn802a   "Location of accident"
label variable qn802b   "What object was the accident with"
label variable qn802c   "Was it a non-road traffic accident"
label variable qn803    "Injury was intentional"
label variable qn804    "Baby suffered from animal/insect bite"
label variable qn805    "Type of animal/insect"
label variable qn901a   "Age when illness started"
label variable qn901b   "Was baby growing normally before illness"
label variable qn901c   "Number of days baby was ill before death"
label variable qn901    "Baby able to suckle or bottle-feed"
label variable qn902u   "Time after birth baby suckled or bottle-fed (Units)"
label variable qn902n   "Time after birth baby suckled or bottle-fed (Number)"
label variable qn903    "Baby stopped suckling or bottle feeding"
label variable qn904    "Days after birth baby stopped suckling or bottle feeding"
label variable qn905    "Breastfeeding was exclusive"
label variable qn906    "Baby had convulsions"
label variable qn907    "Days after birth convulsions started"
label variable qn908    "Baby become stiff and arched backwards"
label variable qn909    "Baby had bulging of the fontanelle"
label variable qn910    "Days after birth baby had bulging"
label variable qn910a   "Baby's head fontanelle was sunken"
label variable qn910b   "Days after birth head have the sunken part"
label variable qn911    "Baby became unresponsive or unconscious"
label variable qn912    "Days after birth baby became unresponsive or unconscious"
label variable qn912a   "Baby become unresponsive"
label variable qn912b   "Baby became unresponsive 24 hours before death"
label variable qn913    "Baby had fever"
label variable qn914    "Days after birth baby had fever"
label variable qn914a   "Fever continued until death"
label variable qn915    "Baby became cold to touch"
label variable qn916    "Days after birth baby became cold to touch"
label variable qn917    "Baby had a cough"
label variable qn918    "Days after birth baby start to cough"
label variable qn919    "Baby had fast breathing"
label variable qn920    "Days after birth baby started breathing fast"
label variable qn921    "Baby had difficulty of breathing"
label variable qn922    "Days after birth baby started to have difficulty of breathing"
label variable qn922a   "Length of difficulty breathing"
label variable qn922b   "Baby became lethargic after normal activity"
label variable qn923    "Baby had chest indrawing"
label variable qn924    "Baby had grunting"
label variable qn925    "Baby had flaring of the nostrils"
label variable qn926    "Baby had diarrhea"
label variable qn927    "Days after birth baby had diarrhea"
label variable qn927a   "Length of diarrhea"
label variable qn928    "Times baby passed stools in a day"
label variable qn929    "Blood in the stools"
label variable qn930    "Baby had vomiting"
label variable qn931    "Days after birth baby started vomiting"
label variable qn932    "Times baby vomited in a day"
label variable qn932a   "Vomited in the week preceding death"
label variable qn933    "Baby had abdominal distension"
label variable qn934    "Days after birth baby had abdominal distension"
label variable qn935    "Baby had redness or discharge from umblical cord"
label variable qn936    "Baby had pustular skin rash"
label variable qn937    "Baby had yellow palms or soles"
label variable qn938    "Days after birth baby had yellow palms or soles"
label variable qn939    "Days the baby had yellow palms or soles"
label variable qn939a   "Baby appeared healthy then died suddenly"
label variable qn1001   "Age of mother when the baby died"
label variable qn1002   "Mother received antenatal care"
label variable qn1002a  "Pregnancy complications in the last 3 months of pregnancy"
label variable qn1002b  "Color of water when it broke"
label variable qn1002c  "Mother received vaccines during pregnancy"
label variable qn1002d  "Mother had fever during labor"
label variable qn1002e  "Mother had high BP during last three months of pregnancy"
label variable qn1002f  "Mother had diabetes mellitus"
label variable qn1002g  "Mother had foul smelling vaginal discharge"
label variable qn1002h  "Mother had convulsions in last three months of pregnancy, labor or delivery"
label variable qn1002i  "Mother had blurred vision during the last three months of pregnancy"
label variable qn1002j  "Mother had severe anemia"
label variable qn1002k  "Mother had vaginal bleeding during the last three months of pregnancy"
label variable qn1003   "Mother received TT vaccine"
label variable qn1004   "Number of doses of TT vaccine"
label variable qn1005   "Current health status of the mother"
label variable qn1005a  "Mother been tested for HIV"
label variable qn1005b  "Mother told she had HIV/AIDS"
label variable qn1101   "Baby received any treatment for the illness"
label variable qn1101a  "Baby received ORS"
label variable qn1101b  "Baby needed ORS"
label variable qn1101c  "Baby received IV fluids"
label variable qn1101d  "Baby needed IV fluids"
label variable qn1101e  "Baby received blood transfusions"
label variable qn1101f  "Baby needed blood transfusion"
label variable qn1101g  "Baby received food from tube in nose"
label variable qn1101h  "Baby needed food from tube in nose"
label variable qn1101i  "Baby received injectable antibiotics"
label variable qn1101j  "Baby needed injectable antibiotics"
label variable qn1101k  "Baby received ART"
label variable qn1101l  "Baby needed ART"
label variable qn1101m  "Baby had operation for illness"
label variable qn1101n  "Baby needed operation for illness"
label variable qn1102   "Treatment for the baby"
label variable qn1103   "Place of treatment for the baby"
label variable qn1104   "Number of formal contacts with health services"
label variable qn1104a  "Name of hospital where help was sought"
label variable qn1104b  "Used motorized transport to get to hospital"
label variable qn1104c  "Problems at hospital admission"
label variable qn1104d  "Problems with medical treatment"
label variable qn1104e  "Problems getting medication or medical tests"
label variable qn1104f  "Took more than two hours to get to hospital"
label variable qn1104g  "Doubts medical care was needed in baby's final days"
label variable qn1104h  "Traditional medicine used in final days before death"
label variable qn1104i  "Called for help in final days before death"
label variable qn1104j  "Medical costs prohibited other household payments"
label variable qn1105   "Health care worker told cause of death"
label variable qn1106   "Health care worker comments"
label variable qn1201   "Birth registered"
label variable qn1202   "Birth registration number"
label variable qn1203d  "Date of birth registration(day)"
label variable qn1203m  "Date of birth registration(month)"
label variable qn1203y  "Date of birth registration (year)"
label variable qn1204   "Was death registered"
label variable qn1205   "Death registration number"
label variable qn1206d  "Date of death registration(day)"
label variable qn1206m  "Date of death registration (month)"
label variable qn1206y  "Date of death registration (year)"
label variable qn1207   "Cause of death from first top of Birth Certificate"
label variable qn1208   "Cause of death from second line from Brth Certificate"
label variable qn1209   "Cause of death from third line of Birth Certificate"
label variable qn1210   "Cause of death from fourth line of Birth Certificate"
label variable qn1211   "Contributory cause of death from death certificate (chapter 2)"
label variable qn1301   "Other health records available"
label variable qn1303   "Burial permit (Cause of Death)"
label variable qn1304   "Post mortem results (Cause of Death)"
label variable qn1305   "Vaccination card"
label variable qn1306   "Hospital prescription"
label variable qn1307   "Treatment cards"
label variable qn1308   "Hospital discharge"
label variable qn1309   "Laboratory results"
label variable qn1310   "Other hospital documents"
label variable qn1311h  "End of interview (Hour)"
label variable qn1311m  "End of interview (Minutes)"
label variable qc201h   "Start of interview (Hour)"
label variable qc201m   "Start of interview (Minutes)"
label variable qc203    "Relationship to deceased"
label variable qc204    "Lived with the deceased"
label variable qc302    "Sex of Deceased"
label variable qc303d   "Date of Birth (Day)"
label variable qc303m   "Date of Birth (Month)"
label variable qc303y   "Date of Birth (year)"
label variable qc303a   "Season when died"
label variable qc304u   "Age of deceased (Units)"
label variable qc304n   "Age of deceased (Number)"
label variable qc305d   "Date deceased die (Day)"
label variable qc305m   "Date deceased die (Month)"
label variable qc305y   "Date deceased die (Year)"
label variable qc307    "Place deceased died"
label variable qc401    "Events that lead to death"
label variable qc402    "Cause of death 1"
label variable qc403    "Cause of death 2"
label variable qc403a   "Illness that led to death mentioned"
label variable qc502    "Heart disease"
label variable qc503    "Diabetes"
label variable qc504    "Asthma"
label variable qc505    "Epilepsy"
label variable qc506    "Malnutrition"
label variable qc507    "Cancer"
label variable qc508    "Specify type of cancer"
label variable qc509    "Tuberclosis"
label variable qc510    "HIV/AIDS"
label variable qc510a   "Positive test for malaria"
label variable qc510b   "Negative test for malaria"
label variable qc510c   "Dengue fever"
label variable qc510d   "Measles"
label variable qc510e   "Sickle cell"
label variable qc510f   "Kidney disease"
label variable qc510g   "Liver disease"
label variable qc511    "Suffered from any other medically diagnosed illness"
label variable qc512    "Specify illness"
label variable qc601    "Suffered from any injury or accident"
label variable qc602    "Kind of injury or accident"
label variable qc602a   "Location of accident"
label variable qc602b   "What object was the accident with"
label variable qc602c   "Was it a non-road traffic accident"
label variable qc603    "Injury/accident was intentional by someone else"
label variable qc606    "Suffered from animal/insects bite"
label variable qc607    "Type of animal/insect"
label variable qc701    "Child was small at birth"
label variable qc702    "Child born prematurely"
label variable qc703u   "Duration of pregnancy (Units)"
label variable qc703n   "Duration pregnancy (Number)"
label variable qc704    "Child grown normally"
label variable qc704a   "Birth weight"
label variable qc704b   "Body part was too big/small at birth"
label variable qc704c   "Swelling or defect on back at birth"
label variable qc704d   "Large head at birth"
label variable qc704e   "Small head at birth"
label variable qc705    "Child had bulging of the fontanelle"
label variable qc706    "Days before death had bulging"
label variable qc801    "Mother's health now"
label variable qc801a   "Received professional assitance during delivery"
label variable qc801b   "Mother was tested for HIV"
label variable qc801c   "Mother told she has HIV/AIDS"
label variable qc802u   "Duration of illness (Units)"
label variable qc802n   "Duration of illness (Numbers)"
label variable qc802a   "Appeared healthy then died"
label variable qc803    "Had fever"
label variable qc804u   "Duration of fever (Units)"
label variable qc804n   "Duration of fever (Numbers)"
label variable qc805    "Severity of fever"
label variable qc806    "Fever was continuous"
label variable qc807    "Had chills/rigor"
label variable qc807a   "Had night sweats"
label variable qc808    "Had cough"
label variable qc809u   "Duration of cough (Units)"
label variable qc809n   "Duration of cough (Number)"
label variable qc809a   "Cough productive with sputum"
label variable qc809b   "Cough contained blood"
label variable qc809c   "Cough with whooping sound"
label variable qc810    "Severity of cough"
label variable qc811    "Child vomited after cough"
label variable qc812    "Child had fast breathing"
label variable qc813    "Duration of fast breathing (days)"
label variable qc814    "Difficulty in breathing"
label variable qc815    "Duration of difficulty in breathing (days)"
label variable qc816    "Had chest indrawing"
label variable qc817    "Duration of chest indrawing (days)"
label variable qc818    "Had noisy breathing"
label variable qc819    "Had flaring of nostrils"
label variable qc820    "Had diarrhea"
label variable qc821    "Duration of diarrhea (days)"
label variable qc822    "Number of times passed stool in a day"
label variable qc823    "Blood in stool during the final illness"
label variable qc824    "Had vomiting"
label variable qc825    "Duration of vomiting (days)"
label variable qc826    "Number of vomits in a day"
label variable qc826a   "Vomit blood"
label variable qc826b   "Vomit colored black"
label variable qc827    "Had abdominal pain"
label variable qc828u   "Duration of abdominal pain (units)"
label variable qc828n   "Duration of abdominal pain"
label variable qc829    "Abdominal pain was severe"
label variable qc830    "Had abdominal distension"
label variable qc831u   "Duration of abdominal distension (Units)"
label variable qc831n   "Duration of abdominal distension (Number)"
label variable qc832    "Development of distension"
label variable qc833    "Not passed any stool for a day or longer"
label variable qc833a   "Portruding abdomen"
label variable qc833bu  "Protruding abdomen unit"
label variable qc833bn  "Protruding abdomen number"
label variable qc834    "Had a mass in the abdomen"
label variable qc835u   "Duration of mass in the abdomen (Units)"
label variable qc835n   "Duration of mass in the abdomen (Number)"
label variable qc836    "Had headache"
label variable qc837u   "Duration of headache (Units)"
label variable qc837n   "Duration of headache (Number)"
label variable qc838    "Severity of headache"
label variable qc839    "Had stiff or painful neck"
label variable qc840    "Duration of stiff or painful neck"
label variable qc841    "Became unconscious"
label variable qc842    "Duration of unconsciousness (days)"
label variable qc843    "Development of unconsciousness"
label variable qc844    "Had convulsions"
label variable qc844a   "Convulsions occured in whole body"
label variable qc845u   "Duration of convulsions (units)"
label variable qc845n   "Duration of convulsions (numbers)"
label variable qc846    "Had paralysis of lower limbs"
label variable qc847u   "Duration of paralysis of lower limbs (units)"
label variable qc847n   "Duration of paralysis of lower limbs (number)"
label variable qc848    "Development of paralysis"
label variable qc849    "Change in amount of urine passed daily"
label variable qc850u   "Durations change in amount of urine passed daily (Units)"
label variable qc850n   "Durations change in amount of urine passed daily (Number)"
label variable qc851    "Amount of urine passed"
label variable qc851a   "Blood in urine"
label variable qc852    "Had skin rash"
label variable qc853    "Duration of skin rash"
label variable qc854a   "Rash on face"
label variable qc854b   "Rash on trunk"
label variable qc854c   "Rash on arms and legs"
label variable qc854d   "Rash on other places"
label variable qc855    "Appearance of the rash"
label variable qc856    "Had red eyes"
label variable qc857    "Had bleeding from nose, mouth and anus"
label variable qc858    "Had weight loss"
label variable qc859u   "Duration of weight loss before death (Units)"
label variable qc859n   "Duration of weight loss before death (Number)"
label variable qc860    "Looked very thin and wasted"
label variable qc860a   "Sores or ulcers"
label variable qc860b   "Sores had clear fluid or pus"
label variable qc860c   "Ulcer was on the foot"
label variable qc860d   "Ulcer foot ooze pus"
label variable qc860e   "Days foot oozed pus"
label variable qc861    "Had mouth sores or white patches in the mouth"
label variable qc862    "Duration of mouth sores (days)"
label variable qc863    "Had swelling"
label variable qc864u   "Duration of swelling (Units)"
label variable qc864n   "Duration of swelling (Number)"
label variable qc864aa  "Swelling on the face"
label variable qc864ab  "Swelling on the joints"
label variable qc864ac  "Swelling on the ankles"
label variable qc864ad  "Swelling on the whole body"
label variable qc864ae  "Swelling on other places"
label variable qc864b   "Swollen legs"
label variable qc864c   "Areas of skin that was black"
label variable qc864d   "Difficulty swallowing"
label variable qc864e   "Amount of days of difficulty swallowing"
label variable qc864f   "Difficulty swallowing solid liquids or both"
label variable qc866    "Had any lumps"
label variable qc867u   "Duration of lumps (Units)"
label variable qc867n   "Duration of lumps (Number)"
label variable qc868a   "Lumps on neck"
label variable qc868b   "Lumps on armpit"
label variable qc868c   "Lumps on groin"
label variable qc868d   "Lumps on other places"
label variable qc869    "Had yellow discoloration of the eye"
label variable qc870u   "Duration of yellow discoloration of the eye (Units)"
label variable qc870n   "Duration of yellow discoloration of the eye (Number)"
label variable qc871    "Hair changed to reddish/yellowish"
label variable qc872u   "Duration of hair changed to reddish/yellowish (Units)"
label variable qc872n   "Duration of hair changed to reddish/yellowish (Number)"
label variable qc873    "Look pale or had pale palms"
label variable qc874    "Duration of looking pale (days)"
label variable qc875    "Had sunken eyes"
label variable qc876    "Duration of having sunken eyes"
label variable qc901    "Vaccinated for measles"
label variable qc901a   "Has vaccination card"
label variable qc901b   "Vaccine card received"
label variable qc902    "Recieved treatment for illness that led to death"
label variable qc903    "Drugs given for illness"
label variable qc904aa  "ORS or IV fluids (drip)"
label variable qc904ab  "Blood transfusion"
label variable qc904ac  "Treatment/food through the nose"
label variable qc904ad  "Other treatment"
label variable qc904a   "Child received injectable antibiotics"
label variable qc904b   "Child needed injectable antibiotics"
label variable qc904c   "Child received ART"
label variable qc904d   "Child needed ART"
label variable qc904e   "Received treatment at health facility"
label variable qc905    "Place of treatment"
label variable qc905a   "Travel to hospital before death"
label variable qc905b   "Used motorized transport to get to hospital"
label variable qc905c   "Problems at hospital admission"
label variable qc905d   "Problems with medical treatment"
label variable qc905e   "Problems getting medication or medical tests"
label variable qc905f   "Took more than two hours to get to hospital"
label variable qc905g   "Discharged from hospital very ill"
label variable qc905h   "Doubts medical care was needed"
label variable qc905i   "Traditional medicine used in final days before death"
label variable qc905j   "Phone used to call for help"
label variable qc905k   "Total cost of care prohibited other household payments"
label variable qc906    "Number of contacts with formal health services"
label variable qc907    "Told by health care worker about cause of death"
label variable qc908    "Health care worker comments"
label variable qc909    "Had operation for the illness"
label variable qc910    "Days operation before death"
label variable qc911    "Part of the body operated on"
label variable qc1001   "Have a death certificate for the deceased"
label variable qc1002   "Birth registration number"
label variable qc1003d  "Date of death certificate (day)"
label variable qc1003m  "Date of death certificate (month)"
label variable qc1003y  "Date of death certificate (year)"
label variable qc1004   "Was death registered"
label variable qc1005   "Death registration number"
label variable qc1006d  "Date of death certificate (day)"
label variable qc1006m  "Date of death certificate (month)"
label variable qc1006y  "Date of death certificate (year)"
label variable qc1007   "Cause of death from first top of Birth Certificate"
label variable qc1008   "Cause of death from second line from Brth certificate"
label variable qc1009   "Cause of death from third line of birth certificate"
label variable qc1010   "Cause of death from fourth line of birth certificate"
label variable qc1101   "Other health records available"
label variable qc1103   "Burial permit (Cause of Death)"
label variable qc1104   "Post mortem results"
label variable qc1105   "Vaccination card"
label variable qc1106   "Hospital prescription"
label variable qc1107   "Treatment cards"
label variable qc1108   "Hospital discharge"
label variable qc1109   "Laboratory results"
label variable qc1110   "Other hospital documents"
label variable qc1111h  "End of Interview (Hour)"
label variable qc1111m  "End of Interview (Minutes)"

#delimit ;
label define QFORM   
     1 "Form 1 (0-28 days)"
     2 "Form 2 (29 days - <5 years)"
;
label define QNDIVISION
     1 "Barisal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Mymensingh"
     6 "Rajshahi"
     7 "Rangpur"
     8 "Sylhet"
;
label define QNRESIDENCE
     1 "Rural"
     2 "City Corporation"
     3 "Other Urban"
;
label define QNRESULT
     1 "Completed"
     2 "No household member at home"
     3 "Mother/Knowledgable respondent not present"
     4 "Mother or Knowledgable respondent postponed"
     5 "Mother or Knowledgable respondent refused"
     6 "Dwelling vacant/destroyed/not found"
     7 "Other"
;
label define QFINICD 
     1 "Neonatal tetanus"
     2 "Congenital abnormality"
     3 "Drowning"
     4 "Birth asphyxia"
     5 "Birth injury"
     6 "Diarrhoea"
     7 "Pneumonia"
     8 "Neonatal jaundice"
     9 "Pre term birth"
    10 "Possible serious infection"
    11 "Malnutrition"
    12 "Other causes"
    13 "Unspecific"
    14 "Undetermined"
;
label define VA_DEFACTO
     1 "De facto"
     2 "Non de facto"
;
label define QN201H  
    97 "Inconsistent"
;
label define QN201M  
    97 "Inconsistent"
;
label define QN203   
     1 "Father"
     2 "Mother"
     3 "Sibling"
     4 "No relation"
     6 "Other relative"
;
label define QN204   
     1 "Yes"
     2 "No"
;
label define QN302   
     2 "Male"
     1 "Female"
;
label define QN303D  
    98 "DK"
;
label define QN303M  
    97 "Inconsistent"
    98 "DK"
;
label define QN303Y  
  9997 "Inconsistent"
  9998 "DK"
;
label define QN303A  
     1 "Summer"
     2 "Monsoon"
     3 "Autumn"
     4 "Late autumn"
     5 "Winter"
     6 "Spring"
     8 "Don't know"
;
label define QN305D  
    98 "DK"
;
label define QN305M  
    97 "Inconsistent"
    98 "DK"
;
label define QN305Y  
  9997 "Inconsistent"
  9998 "DK"
;
label define QN307   
     1 "Hospital"
     2 "Other Health Facility"
     3 "On the way to a health facility or provider"
     4 "Home"
     6 "Other"
     8 "Don't know"
;
label define QN502   
    98 "Don't know"
;
label define QN503U  
     1 "Months"
     2 "Weeks"
     9 "Special answers"
;
label define QN503N  
    98 "Don't know"
    99 "Missing"
;
label define QN504   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN505   
    98 "Don't know"
;
label define QN506A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN506B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN506C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN506D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN506E  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507E  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507F  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507G  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507H  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507I  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN507J  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN508   
     1 "Single"
     2 "Twin"
     3 "Triplet or more"
     8 "Don't know"
;
label define QN509   
     1 "First"
     2 "Second"
     3 "Third or Higher"
     8 "Don't know"
;
label define QN601   
     1 "Hospital"
     2 "Other Health facility"
     3 "Home"
     6 "Other"
     8 "Don't know"
;
label define QN603   
     1 "Before labor start"
     2 "During labor"
     3 "Water did not break"
     8 "Don't know"
;
label define QN604   
     1 "Less than 24 hours"
     2 "24 hours or more"
     8 "Don't know"
;
label define QN605   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN606   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN607   
     1 "Before labor start"
     2 "During labor"
     8 "Don't know"
;
label define QN608   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN609   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN610   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN611   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN612   
     1 "Less than 12 hours"
     2 "12 - 23 hours"
     3 "24 hours or more"
     4 "Did not have labor pains"
     8 "Don't know"
;
label define QN613   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN614   
     1 "Forceps/Vacuum"
     2 "Caesarean section"
     6 "Other"
     8 "Don't know"
;
label define QN615   
     1 "Head"
     2 "Bottom"
     3 "Feet"
     4 "Arm/Head"
     6 "Other"
     8 "Don't know"
;
label define QN616   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN701   
     1 "Smaller than normal"
     2 "Normal"
     3 "Larger than normal"
     8 "Don't know"
     9 "Missing"
;
label define QN701A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN702   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN703U  
     1 "Months"
     2 "Weeks"
     9 "Special answers"
;
label define QN703N  
    98 "Don't know"
;
label define QN705   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN707   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN709   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN710   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN712   
     1 "Normal"
     2 "Pale"
     3 "Blue"
     8 "Don't know"
;
label define QN713   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN714   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN715   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN716   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN718   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN719   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN801   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN802   
     1 "Road traffic accident"
     2 "Fall"
     3 "Drowning"
     4 "Poisoning"
     5 "Burns"
     6 "Violence/Assault"
     7 "Fall from height"
     8 "Injured by firearms"
     9 "Stab injury"
    10 "Hanging/strangulation"
    11 "Blunt force injury"
    12 "Natural calamities"
    13 "Electrocution"
    96 "Other"
    98 "Don't know"
;
label define QN802A  
     1 "Pedestrian"
     2 "In a car/small vehicle"
     3 "In a bus/large vhicle"
     4 "On a motorised cycle"
     5 "On a non-motorised cycle"
     6 "Other"
;
label define QN802B  
     1 "Pedestrian"
     2 "In a car/small vehicle"
     3 "In a bus/large vhicle"
     4 "On a motorised cycle"
     5 "On a non-motorised cycle"
     6 "Other"
;
label define QN802C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN803   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN804   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN805   
     1 "Dog"
     2 "Snake"
     3 "Insect"
     6 "Other"
     8 "Don't know"
;
label define QN901A  
    98 "Don't know"
;
label define QN901B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN901C  
    98 "Don't know"
;
label define QN901   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN902U  
     1 "Hours"
     2 "Days"
     9 "Special answers"
;
label define QN902N  
    98 "Don't know"
;
label define QN903   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN904   
    98 "Don't know"
;
label define QN905   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN906   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN907   
    98 "Don't know"
;
label define QN908   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN909   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN910   
    98 "Don't know"
;
label define QN910A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN910B  
    98 "Don't know"
;
label define QN911   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN912   
    98 "Don't know"
;
label define QN912A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN912B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN913   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN914   
    98 "Don't know"
;
label define QN914A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN915   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN916   
    98 "Don't know"
;
label define QN917   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN918   
    98 "Don't know"
;
label define QN919   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN920   
    98 "Don't know"
;
label define QN921   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN922   
    98 "Don't know"
;
label define QN922A  
    98 "Don't know"
;
label define QN922B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN923   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN924   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN925   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN926   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN927   
    98 "Don't know"
;
label define QN927A  
    98 "Don't know"
;
label define QN928   
    98 "Don't know"
;
label define QN929   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN930   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN931   
    98 "Don't know"
;
label define QN932   
    98 "Don't know"
;
label define QN932A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN933   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN934   
    98 "Don't know"
;
label define QN935   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN936   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN937   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN938   
    98 "Don't know"
;
label define QN939   
    98 "Don't know"
;
label define QN939A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1001  
    98 "Don't know"
;
label define QN1002  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002A 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002B 
     1 "Green or brown"
     2 "Clear"
     3 "Water did not break"
     6 "Other"
     8 "Don't know"
;
label define QN1002C 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002D 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002E 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002F 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002G 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002H 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002I 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002J 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1002K 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1003  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1004  
    98 "Don't know"
;
label define QN1005  
     1 "Healthy"
     2 "Ill"
     8 "Don't know"
;
label define QN1005A 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1005B 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101A 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101B 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101C 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101D 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101E 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101F 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101G 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101H 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101I 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101J 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101K 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101L 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101M 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1101N 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104  
    98 "Don't know"
;
label define QN1104B 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104C 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104D 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104E 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104F 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104G 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104H 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104I 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1104J 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1105  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1201  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1203D 
    99 "Missing"
;
label define QN1203M 
    99 "Missing"
;
label define QN1203Y 
  9999 "Missing"
;
label define QN1204  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QN1205  
999999998 "Don't know"
;
label define QN1206D 
    99 "Missing"
;
label define QN1206M 
    99 "Missing"
;
label define QN1206Y 
  9999 "Missing"
;
label define QN1301  
     1 "Yes"
     2 "No"
;
label define QN1311H 
    97 "Inconsistent"
;
label define QN1311M 
    97 "Inconsistent"
;
label define QC201H  
    97 "Inconsistent"
;
label define QC201M  
    97 "Inconsistent"
;
label define QC203   
     1 "Father"
     2 "Mother"
     3 "Sibling"
     4 "No relation"
     6 "Other Relative"
;
label define QC204   
     1 "Yes"
     2 "No"
;
label define QC302   
     2 "Male"
     1 "Female"
;
label define QC303D  
    98 "DK"
;
label define QC303M  
    97 "Inconsistent"
    98 "DK"
;
label define QC303Y  
  9997 "Inconsistent"
  9998 "DK"
;
label define QC303A  
     1 "Summer"
     2 "Monsoon"
     3 "Autumn"
     4 "Late autumn"
     5 "Winter"
     6 "Spring"
     8 "Don't know"
;
label define QC304U  
     1 "Age in days"
     2 "Age in months"
     9 "Special answers"
;
label define QC304N  
    99 "Missing"
;
label define QC305D  
    98 "Don't know"
;
label define QC305M  
    97 "Inconsistent"
    98 "DK"
;
label define QC305Y  
  9997 "Inconsistent"
  9998 "DK"
;
label define QC307   
     1 "Hospital"
     2 "Other health facility"
     3 "On the way to health facility or provider"
     4 "Home"
     6 "Other"
     8 "Don't know"
;
label define QC502   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC503   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC504   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC505   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC506   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC507   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC509   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510E  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510F  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC510G  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC511   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC601   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC602   
     1 "Road traffic accident"
     2 "Fall"
     3 "Drowning"
     4 "Poisoning"
     5 "Burns"
     6 "Violence/assault"
     7 "Fall from height"
     8 "Injured by firearms"
     9 "Stab injury"
    10 "Hanging strngulation"
    11 "Blunt force injury"
    12 "Natural calamities"
    13 "Electrocution"
    96 "Other"
;
label define QC602A  
     1 "Pedestrian"
     2 "In a car/small vehicle"
     3 "In a bus/large vhicle"
     4 "On a motorised cycle"
     5 "On a non-motorised cycle"
     6 "Other"
;
label define QC602B  
     1 "Pedestrian"
     2 "In a car/small vehicle"
     3 "In a bus/large vhicle"
     4 "On a motorised cycle"
     5 "On a non-motorised cycle"
     6 "Other"
;
label define QC602C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC603   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC606   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC607   
     1 "Dog"
     2 "Snake"
     3 "Insect"
     6 "Other"
     8 "Don't know"
;
label define QC701   
     1 "Smaller than normal"
     2 "Normal"
     3 "Larger than normal"
     8 "Don't know"
;
label define QC702   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC703U  
     1 "Weeks"
     2 "Months"
     9 "Special answers"
;
label define QC703N  
    98 "Don't know"
;
label define QC704   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC704B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC704C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC704D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC704E  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC705   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC706   
    98 "Don't know"
;
label define QC801   
     1 "Healthy"
     2 "Ill"
     8 "Don't know"
;
label define QC801A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC801B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC801C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC802U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC802N  
    98 "Don't know"
;
label define QC802A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC803   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC804U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC804N  
    98 "Don't know"
;
label define QC805   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC806   
     1 "Continuous"
     2 "On and off"
     8 "Don't know"
;
label define QC807   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC807A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC808   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC809U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC809N  
    98 "Don't know"
;
label define QC809A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC809B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC809C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC810   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC811   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC812   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC813   
    98 "Don't know"
;
label define QC814   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC815   
    98 "Don't know"
;
label define QC816   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC817   
    98 "Don't know"
;
label define QC818   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC819   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC820   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC821   
    98 "Don't know"
;
label define QC822   
    98 "Don't know"
;
label define QC823   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC824   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC825   
    98 "Don't know"
;
label define QC826   
    98 "Don't know"
;
label define QC826A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC826B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC827   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC828U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC828N  
    98 "Don't know"
;
label define QC829   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC830   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC831U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC831N  
    98 "Don't know"
;
label define QC832   
     1 "Rapidly within days"
     2 "Gradually over months"
     8 "Don't know"
;
label define QC833   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC833BU 
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC833BN 
    98 "Don't know"
;
label define QC834   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC835U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC835N  
    98 "Don't know"
;
label define QC836   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC837U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC837N  
    98 "Don't know"
;
label define QC838   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC839   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC840   
    98 "Don't know"
;
label define QC841   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC842   
    98 "Don't know"
;
label define QC843   
     1 "Suddenly"
     2 "Fast (in a day)"
     3 "Slowly (many days)"
     8 "Don't know"
;
label define QC844   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC844A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC845U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC845N  
    98 "Don't know"
;
label define QC846   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC847U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC847N  
    98 "Don't know"
;
label define QC848   
     1 "Suddenly"
     2 "Fast (in a day)"
     3 "Slowly (many days)"
     8 "Don't know"
;
label define QC849   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC850U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC850N  
    98 "Don't know"
;
label define QC851   
     1 "Too much"
     2 "Too little"
     3 "No urine at all"
     8 "Don't know"
;
label define QC851A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC852   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC853   
    98 "Don't know"
;
label define QC854A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC854B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC854C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC854D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC855   
     1 "Measles rash"
     2 "Rash with clear fluid"
     3 "Rash with pus"
     8 "Don't know"
;
label define QC856   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC857   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC858   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC859U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC859N  
    98 "Don't know"
;
label define QC860   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC860A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC860B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC860C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC860D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC860E  
    98 "Don't know"
;
label define QC861   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC862   
    98 "Don't know"
;
label define QC863   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC864N  
    98 "Don't know"
;
label define QC864AA 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864AB 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864AC 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864AD 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864AE 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC864E  
    98 "Don't know"
;
label define QC864F  
     1 "Solid"
     2 "Liquid"
     3 "Both"
;
label define QC866   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC867U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC867N  
    98 "Don't know"
;
label define QC868A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC868B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC868C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC868D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC869   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC870U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC870N  
    98 "Don't know"
;
label define QC871   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC872U  
     1 "Days"
     2 "Months"
     9 "Special answers"
;
label define QC872N  
    98 "Don't know"
;
label define QC873   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC874   
    98 "Don't know"
;
label define QC875   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC876   
    98 "Don't know"
;
label define QC901   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC901A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC902   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904AA 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904AB 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904AC 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904AD 
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC904E  
     1 "Yes"
     2 "No"
;
label define QC905A  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905B  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905C  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905D  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905E  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905F  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905G  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905H  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905I  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905J  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC905K  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC906   
    98 "Don't know"
;
label define QC907   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC909   
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC910   
    98 "Don't know"
;
label define QC911   
     1 "Abdomen"
     2 "Chest"
     3 "Head"
     6 "Other"
     8 "Don't know"
;
label define QC1001  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC1003D 
    99 "Missing"
;
label define QC1003M 
    99 "Missing"
;
label define QC1003Y 
  9999 "Missing"
;
label define QC1004  
     1 "Yes"
     2 "No"
     8 "Don't know"
;
label define QC1005  
999999998 "Don't know"
;
label define QC1006D 
    99 "Missing"
;
label define QC1006M 
    99 "Missing"
;
label define QC1006Y 
  9999 "Missing"
;
label define QC1101  
     1 "Yes"
     2 "No"
;
label define QC1111H 
    97 "Inconsistent"
;
label define QC1111M 
    97 "Inconsistent"
;

#delimit cr
label values qform    QFORM   
label values qndivision QNDIVISION
label values qnresidence QNRESIDENCE
label values qnresult QNRESULT
label values qfinicd  QFINICD 
label values va_defacto VA_DEFACTO
label values qn201h   QN201H  
label values qn201m   QN201M  
label values qn203    QN203   
label values qn204    QN204   
label values qn302    QN302   
label values qn303d   QN303D  
label values qn303m   QN303M  
label values qn303y   QN303Y  
label values qn303a   QN303A  
label values qn305d   QN305D  
label values qn305m   QN305M  
label values qn305y   QN305Y  
label values qn307    QN307   
label values qn502    QN502   
label values qn503u   QN503U  
label values qn503n   QN503N  
label values qn504    QN504   
label values qn505    QN505   
label values qn506a   QN506A  
label values qn506b   QN506B  
label values qn506c   QN506C  
label values qn506d   QN506D  
label values qn506e   QN506E  
label values qn507a   QN507A  
label values qn507b   QN507B  
label values qn507c   QN507C  
label values qn507d   QN507D  
label values qn507e   QN507E  
label values qn507f   QN507F  
label values qn507g   QN507G  
label values qn507h   QN507H  
label values qn507i   QN507I  
label values qn507j   QN507J  
label values qn508    QN508   
label values qn509    QN509   
label values qn601    QN601   
label values qn603    QN603   
label values qn604    QN604   
label values qn605    QN605   
label values qn606    QN606   
label values qn607    QN607   
label values qn608    QN608   
label values qn609    QN609   
label values qn610    QN610   
label values qn611    QN611   
label values qn612    QN612   
label values qn613    QN613   
label values qn614    QN614   
label values qn615    QN615   
label values qn616    QN616   
label values qn701    QN701   
label values qn701a   QN701A  
label values qn702    QN702   
label values qn703u   QN703U  
label values qn703n   QN703N  
label values qn705    QN705   
label values qn707    QN707   
label values qn709    QN709   
label values qn710    QN710   
label values qn712    QN712   
label values qn713    QN713   
label values qn714    QN714   
label values qn715    QN715   
label values qn716    QN716   
label values qn718    QN718   
label values qn719    QN719   
label values qn801    QN801   
label values qn802    QN802   
label values qn802a   QN802A  
label values qn802b   QN802B  
label values qn802c   QN802C  
label values qn803    QN803   
label values qn804    QN804   
label values qn805    QN805   
label values qn901a   QN901A  
label values qn901b   QN901B  
label values qn901c   QN901C  
label values qn901    QN901   
label values qn902u   QN902U  
label values qn902n   QN902N  
label values qn903    QN903   
label values qn904    QN904   
label values qn905    QN905   
label values qn906    QN906   
label values qn907    QN907   
label values qn908    QN908   
label values qn909    QN909   
label values qn910    QN910   
label values qn910a   QN910A  
label values qn910b   QN910B  
label values qn911    QN911   
label values qn912    QN912   
label values qn912a   QN912A  
label values qn912b   QN912B  
label values qn913    QN913   
label values qn914    QN914   
label values qn914a   QN914A  
label values qn915    QN915   
label values qn916    QN916   
label values qn917    QN917   
label values qn918    QN918   
label values qn919    QN919   
label values qn920    QN920   
label values qn921    QN921   
label values qn922    QN922   
label values qn922a   QN922A  
label values qn922b   QN922B  
label values qn923    QN923   
label values qn924    QN924   
label values qn925    QN925   
label values qn926    QN926   
label values qn927    QN927   
label values qn927a   QN927A  
label values qn928    QN928   
label values qn929    QN929   
label values qn930    QN930   
label values qn931    QN931   
label values qn932    QN932   
label values qn932a   QN932A  
label values qn933    QN933   
label values qn934    QN934   
label values qn935    QN935   
label values qn936    QN936   
label values qn937    QN937   
label values qn938    QN938   
label values qn939    QN939   
label values qn939a   QN939A  
label values qn1001   QN1001  
label values qn1002   QN1002  
label values qn1002a  QN1002A 
label values qn1002b  QN1002B 
label values qn1002c  QN1002C 
label values qn1002d  QN1002D 
label values qn1002e  QN1002E 
label values qn1002f  QN1002F 
label values qn1002g  QN1002G 
label values qn1002h  QN1002H 
label values qn1002i  QN1002I 
label values qn1002j  QN1002J 
label values qn1002k  QN1002K 
label values qn1003   QN1003  
label values qn1004   QN1004  
label values qn1005   QN1005  
label values qn1005a  QN1005A 
label values qn1005b  QN1005B 
label values qn1101   QN1101  
label values qn1101a  QN1101A 
label values qn1101b  QN1101B 
label values qn1101c  QN1101C 
label values qn1101d  QN1101D 
label values qn1101e  QN1101E 
label values qn1101f  QN1101F 
label values qn1101g  QN1101G 
label values qn1101h  QN1101H 
label values qn1101i  QN1101I 
label values qn1101j  QN1101J 
label values qn1101k  QN1101K 
label values qn1101l  QN1101L 
label values qn1101m  QN1101M 
label values qn1101n  QN1101N 
label values qn1104   QN1104  
label values qn1104b  QN1104B 
label values qn1104c  QN1104C 
label values qn1104d  QN1104D 
label values qn1104e  QN1104E 
label values qn1104f  QN1104F 
label values qn1104g  QN1104G 
label values qn1104h  QN1104H 
label values qn1104i  QN1104I 
label values qn1104j  QN1104J 
label values qn1105   QN1105  
label values qn1201   QN1201  
label values qn1204   QN1204  
label values qn1205   QN1205  
label values qn1301   QN1301  
label values qn1311h  QN1311H 
label values qn1311m  QN1311M 
label values qc201h   QC201H  
label values qc201m   QC201M  
label values qc203    QC203   
label values qc204    QC204   
label values qc302    QC302   
label values qc303d   QC303D  
label values qc303m   QC303M  
label values qc303y   QC303Y  
label values qc303a   QC303A  
label values qc304u   QC304U  
label values qc305d   QC305D  
label values qc305m   QC305M  
label values qc305y   QC305Y  
label values qc307    QC307   
label values qc502    QC502   
label values qc503    QC503   
label values qc504    QC504   
label values qc505    QC505   
label values qc506    QC506   
label values qc507    QC507   
label values qc509    QC509   
label values qc510    QC510   
label values qc510a   QC510A  
label values qc510b   QC510B  
label values qc510c   QC510C  
label values qc510d   QC510D  
label values qc510e   QC510E  
label values qc510f   QC510F  
label values qc510g   QC510G  
label values qc511    QC511   
label values qc601    QC601   
label values qc602    QC602   
label values qc602a   QC602A  
label values qc602b   QC602B  
label values qc602c   QC602C  
label values qc603    QC603   
label values qc606    QC606   
label values qc607    QC607   
label values qc701    QC701   
label values qc702    QC702   
label values qc703u   QC703U  
label values qc703n   QC703N  
label values qc704    QC704   
label values qc704b   QC704B  
label values qc704c   QC704C  
label values qc704d   QC704D  
label values qc704e   QC704E  
label values qc705    QC705   
label values qc706    QC706   
label values qc801    QC801   
label values qc801a   QC801A  
label values qc801b   QC801B  
label values qc801c   QC801C  
label values qc802u   QC802U  
label values qc802n   QC802N  
label values qc802a   QC802A  
label values qc803    QC803   
label values qc804u   QC804U  
label values qc804n   QC804N  
label values qc805    QC805   
label values qc806    QC806   
label values qc807    QC807   
label values qc807a   QC807A  
label values qc808    QC808   
label values qc809u   QC809U  
label values qc809n   QC809N  
label values qc809a   QC809A  
label values qc809b   QC809B  
label values qc809c   QC809C  
label values qc810    QC810   
label values qc811    QC811   
label values qc812    QC812   
label values qc813    QC813   
label values qc814    QC814   
label values qc815    QC815   
label values qc816    QC816   
label values qc817    QC817   
label values qc818    QC818   
label values qc819    QC819   
label values qc820    QC820   
label values qc821    QC821   
label values qc822    QC822   
label values qc823    QC823   
label values qc824    QC824   
label values qc825    QC825   
label values qc826    QC826   
label values qc826a   QC826A  
label values qc826b   QC826B  
label values qc827    QC827   
label values qc828u   QC828U  
label values qc828n   QC828N  
label values qc829    QC829   
label values qc830    QC830   
label values qc831u   QC831U  
label values qc831n   QC831N  
label values qc832    QC832   
label values qc833    QC833   
label values qc833bu  QC833BU 
label values qc833bn  QC833BN 
label values qc834    QC834   
label values qc835u   QC835U  
label values qc835n   QC835N  
label values qc836    QC836   
label values qc837u   QC837U  
label values qc837n   QC837N  
label values qc838    QC838   
label values qc839    QC839   
label values qc840    QC840   
label values qc841    QC841   
label values qc842    QC842   
label values qc843    QC843   
label values qc844    QC844   
label values qc844a   QC844A  
label values qc845u   QC845U  
label values qc845n   QC845N  
label values qc846    QC846   
label values qc847u   QC847U  
label values qc847n   QC847N  
label values qc848    QC848   
label values qc849    QC849   
label values qc850u   QC850U  
label values qc850n   QC850N  
label values qc851    QC851   
label values qc851a   QC851A  
label values qc852    QC852   
label values qc853    QC853   
label values qc854a   QC854A  
label values qc854b   QC854B  
label values qc854c   QC854C  
label values qc854d   QC854D  
label values qc855    QC855   
label values qc856    QC856   
label values qc857    QC857   
label values qc858    QC858   
label values qc859u   QC859U  
label values qc859n   QC859N  
label values qc860    QC860   
label values qc860a   QC860A  
label values qc860b   QC860B  
label values qc860c   QC860C  
label values qc860d   QC860D  
label values qc860e   QC860E  
label values qc861    QC861   
label values qc862    QC862   
label values qc863    QC863   
label values qc864u   QC864U  
label values qc864n   QC864N  
label values qc864aa  QC864AA 
label values qc864ab  QC864AB 
label values qc864ac  QC864AC 
label values qc864ad  QC864AD 
label values qc864ae  QC864AE 
label values qc864b   QC864B  
label values qc864c   QC864C  
label values qc864d   QC864D  
label values qc864e   QC864E  
label values qc864f   QC864F  
label values qc866    QC866   
label values qc867u   QC867U  
label values qc867n   QC867N  
label values qc868a   QC868A  
label values qc868b   QC868B  
label values qc868c   QC868C  
label values qc868d   QC868D  
label values qc869    QC869   
label values qc870u   QC870U  
label values qc870n   QC870N  
label values qc871    QC871   
label values qc872u   QC872U  
label values qc872n   QC872N  
label values qc873    QC873   
label values qc874    QC874   
label values qc875    QC875   
label values qc876    QC876   
label values qc901    QC901   
label values qc901a   QC901A  
label values qc902    QC902   
label values qc904aa  QC904AA 
label values qc904ab  QC904AB 
label values qc904ac  QC904AC 
label values qc904ad  QC904AD 
label values qc904a   QC904A  
label values qc904b   QC904B  
label values qc904c   QC904C  
label values qc904d   QC904D  
label values qc904e   QC904E  
label values qc905a   QC905A  
label values qc905b   QC905B  
label values qc905c   QC905C  
label values qc905d   QC905D  
label values qc905e   QC905E  
label values qc905f   QC905F  
label values qc905g   QC905G  
label values qc905h   QC905H  
label values qc905i   QC905I  
label values qc905j   QC905J  
label values qc905k   QC905K  
label values qc906    QC906   
label values qc907    QC907   
label values qc909    QC909   
label values qc910    QC910   
label values qc911    QC911   
label values qc1001   QC1001  
label values qc1004   QC1004  
label values qc1005   QC1005  
label values qc1101   QC1101  
label values qc1111h  QC1111H 
label values qc1111m  QC1111M 
